---
- hosts: all
  become: true
  become_user: root
  tasks:
   - name: Copy file
     copy:
         src: /tmp/bla
         dest: /root/
         remote_src: yes
         owner: root
         group: root
         mode: 0755
     when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '7'
