---
- name: deployen vsftpd
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: install vsftpd
    package:
      name: vsftpd
      state: latest
  - name: enable vsftpd
    service: 
      name: vsftpd 
      enabled: true
  - name: maak readme file
    copy:
      content: "welkom in amsterdam!\n"
      dest: /var/ftp/pub/README
      force: no
      mode: 0444
